apiVersion: v1
kind: Service
metadata:
  name: springboot-app
spec:
  type: NodePort
  selector:
    app: springboot-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
