name: CI-CD Workflow

on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin' 

      - name: Build and Test
        run: cd springboot-app && mvn clean package

      - name: Static Code Analysis
        run: |
          cd springboot-app  
          mvn sonar:sonar -Dsonar.login=$SONAR_AUTH_TOKEN -Dsonar.host.url=$SONAR_URL
        env: 
          SONAR_URL: "http://172.210.68.59:9000"
          SONAR_AUTH_TOKEN: ${{ secrets.SONARQUBE }}

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          cd springboot-app
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG
        env:
          IMAGE_NAME: "ariefshaik007/ci-cd-proj"
          IMAGE_TAG: "${{github.run_number}}"

      - name: Update Deployment File
        run: |
          rm -rf java-maven-sonar-argocd-k8s
          git clone https://${{ secrets.GIT_PAT }}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME}.git
          cd ${GIT_REPO_NAME}
          git config user.email "ariefshaik001@gmail.com"
          git config user.name "arief"
          sed -i "s/replaceImageTag/${{ github.run_number }}/g" springboot-app-manifests/deployment.yml
          git add springboot-app-manifests/deployment.yml
          git commit -m "Update deployment image to version ${{ github.run_number }} [skip ci]" || echo "No changes to commit"
          git push https://${{ secrets.GIT_PAT }}@github.com/${GIT_USER_NAME}/${GIT_REPO_NAME} HEAD:master
        env:
          GIT_REPO_NAME: "java-maven-sonar-argocd-k8s"
          GIT_USER_NAME: "ariefshaik7"